### ISSUE TITLE
Textfeld Reset

### ISSUE THREAD

**Issue by burgholzer** [7Magic7Mike7/QDD_Vis#12]
Sollte es nicht eigentlich möglich sein das gesamte Textfeld zu löschen?
Also alles markieren und löschen sollte wieder zum Anfangszustand eines leeren Textfeldes ohne angezeigtem DD führen.
Insbesondere solange noch kein einziger Schritt ausgeführt wurde sollte das möglich sein.

**Comment by 7Magic7Mike7** [comment]
Ist im nächsten Update möglich.
