### ISSUE TITLE
Kommentare

### ISSUE THREAD

**Issue by burgholzer** [7Magic7Mike7/QDD_Vis#14]
Kommentare in qasm files ( `// ...`) bzw. real files (`# ...`) bringen das Highlighting durcheinander.

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/6358767/82822380-fd9def80-9ea5-11ea-97fc-0c87307209fa.png">

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/6358767/82822620-5f5e5980-9ea6-11ea-9eb5-31c12cdbdfe6.png">

**Comment by 7Magic7Mike7** [comment]
Wurde behoben. Um möglicher Verwirrung entgegenzuwirken bekommen Kommentare keine Linenumber. Ansonsten würde ja `Start at line` nicht mehr mit der Linenumber übereinstimmen, da Kommentare keine ausführbaren Operationen sind.
