### ISSUE TITLE
Start at line

### ISSUE THREAD

**Issue by burgholzer** [7Magic7Mike7/QDD_Vis#15]
Entweder ich finde den Use Case nicht, oder da funktioniert was nicht ordentlich.
Ich lade `Alu` durch klicken. Dann will ich z.B. von Zeile 20 starten. Ich gebe also bei `Start at line ` 20 ein und es passiert nichts.
Auch nicht wenn ich dann auf irgendeinen der Play/... Buttons drücke.

**Comment by 7Magic7Mike7** [comment]
Aktuell wird nur direkt beim Laden eines Algorithmus `Start at line` berücksichtigt, da man ja nur beim Laden starten kann (so mein Gedanke).
Sollte aber leicht umzusetzen sein, dass man z.B. einen `Go to line`-Button einführt, der die Funktionaliät auch für "mittendrin" gewährt.
