### ISSUE TITLE
Step duration

### ISSUE THREAD

**Issue by burgholzer** [7Magic7Mike7/QDD_Vis#16]
Gibt man bei Step Duration `-1` ein und startet dann die Diashow so erscheint die Fehlermeldung `Invalid number for step-duration: Only integers allowed!`.
Soweit so gut. Jedoch startet die Diashow dann auf einmal trotzdem mit dem zurückgesetzten Wert 700.
Darüber hinaus lässt die Fehlermeldung vermuten, dass nur Integer Werte funktionieren. Das Programm beschwert sich aber weder bei `700.2` noch `700,5`.

**Comment by 7Magic7Mike7** [comment]
Grundsätzlich behoben. Zusätzlich wird der Fehler nun schon beim Verlassen des entsprechenden Feldes ausgegeben, und nicht erst beim Starten der Diashow.
Dafür wird bei Floats kein Fehler ausgegeben, sondern einfach auf den nächsten int abgerundet (sowohl im Eingabefeld als auch intern bei der stepDuration). Falls das Robert oder dir nicht gefällt, muss ich halt schauen, wie ich das anders löse.
