### ISSUE TITLE
Play Controls Mouse Over

### ISSUE THREAD

**Issue by burgholzer** [7Magic7Mike7/QDD_Vis#18]
Die Buttons unter der Textbox sind zwar mittlerweile schon relativ selbsterklärend, man könnte aber noch ein Mouse Over mit Beschreibungen hinzufügen. `to start`, `back`, `play`/`pause` (je nachdem was gerade an ist), `forward`, `to end`

**Comment by 7Magic7Mike7** [comment]
Tooltips sind im nächsten Update enthalten.
