### ISSUE TITLE
qreg/creg nicht editierbar

### ISSUE THREAD

**Issue by burgholzer** [7Magic7Mike7/QDD_Vis#7]
Lädt man z.B. `Alu` so beginnt das Texthighlighting bei `OPENQASM 2.0`. Versucht man jedoch das `qreg q[5]` oder das `creg c[5]` zu editieren bekommt man die Fehlermeldung `You are not allowed to change already processed lines!`.

Vor dem Start des Algorithmus sollte ich aber sehr wohl noch die Anzahl der Qubits ändern können.

Etwas komplizierter, aber rein theoretisch kann ich sogar während der Berechnung noch Qubits hinzufügen. Das muss aber im Rahmen der BA sicherlich nicht mehr eingebaut werden.

**Comment by 7Magic7Mike7** [comment]
Konnte fürs nächste Deployment ganz einfach mittels `if` repariert werden.
