### ISSUE TITLE
Invalid Algorithm ohne newline

### ISSUE THREAD

**Issue by burgholzer** [7Magic7Mike7/QDD_Vis#8]
Wenn am Ende des Algorithmus keine Newline ist kommt die Fehlermeldung `Invalid Algorithm`.
Da könnte man doch sicher irgendwie sicherstellen, dass das trotzdem funktioniert...

<img width="1701" alt="image" src="https://user-images.githubusercontent.com/6358767/82820100-d9d8aa80-9ea1-11ea-8f1c-9765c1bac3f1.png">

**Comment by 7Magic7Mike7** [comment]
Ist im nächsten Deployment behoben. Ich füge einfach eine Newline hinzu, wenn diese fehlt. Da ich deshalb den Inhalt des Textfeldes auch neu setzen muss, könnte das bei sehr langen Algorithmen ein Performance-Problem sein, aber bei add6_196.real mit 262 179 Zeilen ist sowieso das ganze Laden performance-technisch suboptimal, also weiß ich nicht inwiefern das tatsächlich ein Problem ist, bzw. ob ich überhaupt viel dagegen machen kann (vielleicht sind TextAreas einfach nicht ausgelegt für soviel Text).
Deshalb würde ich es derzeit bei dieser einfachen Lösung belassen, und mal schauen ob es überhaupt ungut auffällt.
